from reportlab.lib.pagesizes import A4
from reportlab.platypus import SimpleDocTemplate, Paragraph, Spacer, Table, TableStyle
from reportlab.lib.styles import getSampleStyleSheet
from reportlab.lib import colors
from reportlab.lib.units import inch
from datetime import datetime, timezone
import io


def generate_pdf(memo: dict) -> bytes:
    buf = io.BytesIO()
    doc = SimpleDocTemplate(
        buf, pagesize=A4,
        rightMargin=72, leftMargin=72,
        topMargin=72, bottomMargin=18
    )
    styles = getSampleStyleSheet()
    story = []

    story.append(Paragraph("SMART INVESTOR PRO", styles["Title"]))
    story.append(Paragraph("Due Diligence Investment Memo", styles["Heading2"]))
    story.append(Spacer(1, 6))

    company = memo.get("company_name", "N/A")
    ts = memo.get("timestamp", datetime.now(timezone.utc).isoformat())
    if isinstance(ts, str):
        ts_display = ts[:10]
    else:
        ts_display = ts.strftime("%Y-%m-%d") if hasattr(ts, "strftime") else str(ts)[:10]

    story.append(Paragraph(f"Company: {company}  |  Date: {ts_display}", styles["Normal"]))
    story.append(Spacer(1, 8))

    disclaimer_text = (
        "DISCLAIMER: This analysis is for informational purposes only and does not constitute "
        "investment advice under MiFID II. Investments carry risks including total loss of capital. "
        "Past performance is not indicative of future results. Independent due diligence required."
    )
    disc_style = styles["Normal"]
    disc_style.textColor = colors.HexColor("#CC0000")
    disc_style.fontSize = 8
    story.append(Paragraph(disclaimer_text, disc_style))
    story.append(Spacer(1, 16))

    action = memo.get("recommended_action", "N/A")
    confidence = memo.get("confidence_score", 0)
    if isinstance(confidence, (int, float)):
        conf_pct = f"{confidence * 100:.0f}%"
    else:
        conf_pct = str(confidence)

    header_data = [
        ["Recommendation", action],
        ["Confidence", conf_pct],
        ["Sector", memo.get("sector", "N/A")]
    ]
    header_table = Table(header_data, colWidths=[2*inch, 3*inch])
    header_table.setStyle(TableStyle([
        ("BACKGROUND", (0, 0), (0, -1), colors.HexColor("#1a1a2e")),
        ("TEXTCOLOR", (0, 0), (0, -1), colors.white),
        ("FONTNAME", (0, 0), (0, -1), "Helvetica-Bold"),
        ("FONTSIZE", (0, 0), (-1, -1), 10),
        ("BOTTOMPADDING", (0, 0), (-1, -1), 6),
        ("TOPPADDING", (0, 0), (-1, -1), 6),
        ("GRID", (0, 0), (-1, -1), 0.5, colors.HexColor("#1a1a2e")),
        ("VALIGN", (0, 0), (-1, -1), "MIDDLE"),
    ]))
    story.append(header_table)
    story.append(Spacer(1, 18))

    sections = [
        ("1. Executive Summary",
         f"Action: **{action}** | Confidence: {conf_pct}"),
        ("2. Investment Thesis",
         memo.get("investment_thesis", "Not available.")),
        ("3. Financial Highlights",
         _format_financials(memo.get("financial_highlights", {}))),
        ("4. Market Opportunity",
         memo.get("market_opportunity", "Not available.")),
        ("5. Competitive Advantages",
         _bullet_list(memo.get("competitive_advantages", []))),
        ("6. Key Risks & Mitigation",
         _format_risks(memo.get("key_risks", []))),
        ("7. Regulatory & Compliance",
         "MiFID II suitability check: Pending. GDPR data minimization applied."),
        ("8. Valuation & Price Targets",
         "Basierend auf FreeDataProvider (yfinance/SEC EDGAR). DCF-Model optional in config."),
        ("9. Next Steps",
         "1. Management meeting, verify real-time data via yfinance, draft term sheet.\n"
         "2. Regulatory compliance review")
    ]

    for title, content in sections:
        story.append(Paragraph(title, styles["Heading3"]))
        story.append(Spacer(1, 4))
        story.append(Paragraph(content, styles["Normal"]))
        story.append(Spacer(1, 12))

    story.append(Spacer(1, 20))
    footer_style = styles["Normal"]
    footer_style.fontSize = 7
    footer_style.textColor = colors.grey
    story.append(Paragraph(
        f"Generated by Smart Investor Pro MVP | {datetime.now(timezone.utc).strftime('%Y-%m-%d %H:%M UTC')} | Confidential",
        footer_style
    ))

    doc.build(story)
    buf.seek(0)
    return buf.read()


def _format_financials(data: dict) -> str:
    if not data:
        return "No financial data available."
    lines = []
    for k, v in data.items():
        label = k.replace("_", " ").title()
        lines.append(f"• {label}: {v}")
    return "\n".join(lines)


def _bullet_list(items: list[str]) -> str:
    if not items:
        return "None identified."
    return "\n".join(f"• {item}" for item in items)


def _format_risks(risks: list[dict]) -> str:
    if not risks:
        return "No risks identified."
    lines = []
    for r in risks:
        level = r.get("level", "N/A")
        cat = r.get("category", "N/A")
        desc = r.get("description", "")
        mitigation = r.get("mitigation", "")
        line = f"[{level}] {cat}: {desc}"
        if mitigation:
            line += f"\n  → Mitigation: {mitigation}"
        lines.append(line)
    return "\n\n".join(lines)
