import io
from datetime import datetime, timezone

from reportlab.lib.pagesizes import A4
from reportlab.lib import colors
from reportlab.lib.units import inch, mm
from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
from reportlab.platypus import (
    SimpleDocTemplate, Paragraph, Spacer, Table, TableStyle, PageBreak,
)


def generate_startup_pdf(memo: dict) -> bytes:
    buf = io.BytesIO()
    doc = SimpleDocTemplate(
        buf, pagesize=A4,
        rightMargin=72, leftMargin=72,
        topMargin=72, bottomMargin=18,
    )
    styles = getSampleStyleSheet()
    story = []

    DARK = colors.HexColor("#1a1a2e")
    ACCENT = colors.HexColor("#e94560")
    WHITE = colors.white
    GREY = colors.HexColor("#666666")

    story.append(Paragraph("SMART INVESTOR PRO", styles["Title"]))
    story.append(Paragraph("Startup Due Diligence – Investment Memo", styles["Heading2"]))
    story.append(Spacer(1, 6))

    company = memo.get("company_name", "N/A")
    ts = memo.get("analysis_date", datetime.now(timezone.utc).isoformat())
    ts_display = str(ts)[:10] if ts else datetime.now(timezone.utc).strftime("%Y-%m-%d")
    stage = memo.get("stage", "N/A")

    story.append(Paragraph(f"Company: {company}  |  Stage: {stage}  |  Date: {ts_display}", styles["Normal"]))
    story.append(Spacer(1, 8))

    disc = """
    <font color="#CC0000" size="8">
    <b>DISCLAIMER:</b> Diese Startup-Due-Diligence-Analyse dient ausschliesslich Informationszwecken
    und stellt keine Anlageberatung dar. Investitionen in Startups sind mit hohem Risiko verbunden
    bis hin zum Totalverlust. Eigenständige Due Diligence erforderlich.
    </font>
    """
    story.append(Paragraph(disc, styles["Normal"]))
    story.append(Spacer(1, 16))

    action = memo.get("recommendation", "N/A")
    confidence = memo.get("confidence_score", 0)
    if isinstance(confidence, (int, float)):
        conf_pct = f"{confidence * 100:.0f}%"
    else:
        conf_pct = str(confidence)
    sector = memo.get("sector", "N/A")

    vm = memo.get("visual_metrics") or {}
    vm_score = vm.get("scorecard_total", 0)

    header_data = [
        ["Recommendation", action],
        ["Confidence", conf_pct],
        ["Scorecard", f"{vm_score}/100"],
        ["Sector", sector],
        ["Stage", stage],
    ]
    header_table = Table(header_data, colWidths=[2 * inch, 3 * inch])
    header_table.setStyle(TableStyle([
        ("BACKGROUND", (0, 0), (0, -1), DARK),
        ("TEXTCOLOR", (0, 0), (0, -1), WHITE),
        ("FONTNAME", (0, 0), (0, -1), "Helvetica-Bold"),
        ("FONTSIZE", (0, 0), (-1, -1), 10),
        ("BOTTOMPADDING", (0, 0), (-1, -1), 6),
        ("TOPPADDING", (0, 0), (-1, -1), 6),
        ("GRID", (0, 0), (-1, -1), 0.5, DARK),
        ("VALIGN", (0, 0), (-1, -1), "MIDDLE"),
    ]))
    story.append(header_table)
    story.append(Spacer(1, 18))

    md = memo.get("market_dynamics")
    ca = memo.get("competitive_analysis")
    sa = memo.get("strategic_advice")
    sections = [
        ("1. Investment Thesis", memo.get("investment_thesis", "Not available.")),
    ]
    if md:
        sections.append(("1b. Marktdynamik", md))
    if ca:
        sections.append(("1c. Wettbewerbsvorteil", ca))
    if sa:
        sections.append(("1d. Strategische Empfehlung", sa))
    sections += [
        ("2. Key Strengths", _bullet_list(memo.get("key_strengths", []))),
        ("3. Key Risks & Mitigation", _format_startup_risks(memo.get("key_risks", []))),
        ("4. Scorecard Overview", _format_scorecard(vm, memo.get("confidence_score", 0))),
        ("5. Metrics & Financials", _format_metrics(memo.get("metrics", {}))),
        ("6. DD Checklist", _format_dd_checklist(memo.get("dd_checklist", {}))),
        ("7. Requested Documents", _bullet_list(memo.get("requested_documents", []))),
        ("8. Critical Questions", _numbered_list(memo.get("critical_questions", []))),
        ("9. Pricing Tiers", _format_pricing(memo.get("metrics", {}).get("pricing_tiers", []))),
    ]

    for title, content in sections:
        story.append(Paragraph(title, styles["Heading3"]))
        story.append(Spacer(1, 4))
        if isinstance(content, str):
            story.append(Paragraph(content, styles["Normal"]))
        else:
            for item in content:
                story.append(Paragraph(item, styles["Normal"]))
                story.append(Spacer(1, 2))
        story.append(Spacer(1, 12))

    story.append(Spacer(1, 20))
    story.append(Paragraph(
        f"Generated by Smart Investor Pro MVP | {datetime.now(timezone.utc).strftime('%Y-%m-%d %H:%M UTC')} | Confidential",
        ParagraphStyle("footer", parent=styles["Normal"], fontSize=7, textColor=GREY),
    ))

    doc.build(story)
    buf.seek(0)
    return buf.read()


def _bullet_list(items) -> str:
    if not items:
        return "None identified."
    return "<br/>".join(f"&bull; {item}" for item in items)


def _numbered_list(items) -> list[str]:
    if not items:
        return ["None."]
    return [f"{i+1}. {item}" for i, item in enumerate(items)]


def _format_startup_risks(risks) -> str:
    if not risks:
        return "No risks identified."
    lines = []
    for r in risks:
        level = r.get("severity", r.get("level", "N/A"))
        cat = r.get("category", "N/A")
        desc = r.get("description", "")
        mitigation = r.get("mitigation", "")
        line = f"<b>[{level}] {cat}:</b> {desc}"
        if mitigation:
            line += f"<br/>&rarr; <b>Mitigation:</b> {mitigation}"
        lines.append(line)
    return "<br/><br/>".join(lines)


def _format_metrics(metrics: dict) -> list[str]:
    if not metrics:
        return ["No metrics available."]
    lines = []
    label_map = {
        "tam_eur": "TAM", "sam_eur": "SAM", "som_year3_eur": "SOM (Year 3)",
        "projected_arr_year1": "Projected ARR Year 1", "projected_arr_year3": "Projected ARR Year 3",
        "projected_mrr_year1": "Projected MRR Year 1",
        "target_customers_year1": "Target Customers Year 1", "target_customers_year3": "Target Customers Year 3",
        "gross_margin_pct": "Gross Margin %", "gross_margin_target": "Gross Margin Target",
        "cac_target": "CAC Target", "cac_initial": "CAC Initial",
        "ltv_target": "LTV Target", "ltv_cac_ratio": "LTV/CAC Ratio",
        "payback_months": "Payback (Months)", "payback_weeks": "Payback (Weeks)",
        "churn_rate_monthly": "Monthly Churn Rate",
        "funding_ask_min": "Funding Ask (Min)", "funding_ask_max": "Funding Ask (Max)",
        "total_raised_to_date": "Total Raised to Date",
        "burn_rate_monthly": "Monthly Burn Rate", "runway_months": "Runway (Months)",
        "founder_count": "Founder Count", "technical_founder": "Technical Founder",
        "paying_customers": "Paying Customers", "mrr_current": "Current MRR",
        "mvp_status": "MVP Status",
    }
    for k, v in metrics.items():
        if k == "pricing_tiers":
            continue
        if v is None:
            continue
        label = label_map.get(k, k.replace("_", " ").title())
        if isinstance(v, float):
            if "eur" in k or k.startswith("funding") or "raised" in k:
                val_str = f"EUR {v:,.0f}"
            elif "pct" in k or "margin" in k:
                val_str = f"{v:.1f}%"
            else:
                val_str = f"{v:,.2f}"
        elif isinstance(v, bool):
            val_str = "Yes" if v else "No"
        else:
            val_str = str(v)
        lines.append(f"&bull; <b>{label}:</b> {val_str}")
    if not lines:
        lines.append("No metrics available.")
    return lines


def _format_dd_checklist(checklist: dict) -> str:
    if not checklist:
        return "No checklist available."
    lines = []
    for k, v in checklist.items():
        icon = "&#9989;" if v else "&#10060;"
        label = k.replace("_", " ").title()
        lines.append(f"{icon} {label}")
    return "<br/>".join(lines)


def _format_scorecard(vm: dict, confidence: float) -> str:
    radar = vm.get("radar_scores", {})
    unit = vm.get("unit_economics", {})
    proj = vm.get("projections", {})
    lines = [f"<b>Gesamtscore:</b> {vm.get('scorecard_total', 0)}/100 (Confidence: {confidence:.0%})<br/><br/>"]
    for k, v in sorted(radar.items(), key=lambda x: -x[1]):
        bar = "&#9632;" * int(v) + "&#9632;" * (10 - int(v)) if v <= 10 else "&#9632;" * 10
        lines.append(f"<b>{k.title()}:</b> {bar} {v}/10<br/>")
    lines.append(f"<br/><b>Unit Economics:</b><br/>")
    lines.append(f"&bull; LTV/CAC: {unit.get('ltv_cac_ratio', 'N/A')}:1<br/>")
    if unit.get("payback_months"):
        lines.append(f"&bull; Payback: {unit['payback_months']} Monate<br/>")
    lines.append(f"&bull; Gross Margin: {unit.get('gross_margin_pct', 0):.0f}%<br/>")
    cagr = proj.get("cagr_pct")
    if cagr:
        lines.append(f"&bull; CAGR (Y1-Y3): {cagr:.0f}%<br/>")
    return "".join(lines)


def _format_pricing(tiers: list) -> list[str]:
    if not tiers:
        return ["No pricing tiers available."]
    return [f"&bull; <b>{t.get('plan', 'N/A')}:</b> EUR {t.get('price_eur', 0):,.0f}/mo" + (f" &mdash; {t.get('features', '')}" if t.get("features") else "") for t in tiers]
